name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run_container:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t nginx-demo .

      - name: Run Docker container
        run: docker run -d -p 80:80 nginx-demo
